titles:
  match_any: ["software engineer","swe","backend","back-end","full stack","full-stack"]
weights:
  title_match: 0.15
  new_grad: 0.20
  geo_core: 0.10
  geo_remote_tie: 0.05
new_grad:
  phrases: ["new grad","entry level","university","graduate"]
skills:
  strong:
    Python: 0.08
    Java: 0.07
    "C++": 0.06
    Swift: 0.05
    SQL: 0.05
    MySQL: 0.05
    PostgreSQL: 0.05
    Postgres: 0.05
    MongoDB: 0.04
  web_ops:
    HTML: 0.03
    CSS: 0.03
    Linux: 0.03
    "Power BI": 0.03
  ai_tools:
    LangChain: 0.05
    NumPy: 0.04
    SQLAlchemy: 0.04
    Streamlit: 0.04
    CrewAI: 0.04
    Ollama: 0.04
  ai_group:
    terms: ["Agentic AI","AI Agent","RAG","retrieval-augmented","LLM fine-tuning","multimodal"]
    cap: 0.10
geos:
  core:
    NYC: ["new york","nyc"]
    Seattle: ["seattle"]
    "SF Bay": ["san francisco","sf","san jose","sunnyvale","mountain view","palo alto","redwood city","oakland","berkeley","bay area"]
    LA: ["los angeles","la"]
    "Irvine/OC": ["irvine","orange county","oc"]
  remote_tie_terms: ["remote","hybrid"]
rationale:
  max_tags: 4

