from __future__ import annotations

import json
import logging
from typing import Any

from agentic_jobs.config import settings
from agentic_jobs.services.agents.base import BaseAgent
from agentic_jobs.services.agents.constants import BANNED_PHRASES
from agentic_jobs.services.agents.schemas import CoverLetterDraft, ResearchBrief, ReviewVerdict
from agentic_jobs.services.llm.style_kit import CoverLetterKit


LOGGER = logging.getLogger(__name__)

_SCORING_RUBRIC_TEMPLATE = """
Score on five dimensions (0-2 each, total /10):

1. "So What?" Test (0-2): Does every paragraph answer WHY this matters?
   - 0: States facts without explaining why they matter to the reader
   - 1: Some paragraphs answer "so what" but others are just fact-dumps
   - 2: Every paragraph makes the reader think "I need to talk to this person"

2. Specificity (0-2): Could this letter ONLY be sent to THIS company for THIS role?
   - 0: Swap the company name and nothing changes — generic template
   - 1: Mentions the company but the connection is surface-level
   - 2: Names a specific technical problem the company has and shows relevant work

3. Technical Depth (0-2): Does it show what the candidate actually knows?
   - 0: Vague — "complex patterns", "large datasets", "meaningful impact"
   - 1: Names tools/technologies but doesn't show outcomes
   - 2: Concrete outcomes with numbers, specific tools, and clear results

4. Redundancy & Filler (0-2): Is every sentence doing unique work?
   - 0: Repeats ideas, phrases, or keywords. Says the same thing twice differently.
   - 1: Mostly tight but 1-2 redundant phrases or filler sentences
   - 2: Zero redundancy — every sentence adds new information

5. Voice & Confidence (0-2): Does it sound like a real person, not a template?
   - 0: Corporate language, narrates connections ("this is a natural fit because...")
   - 1: Mostly authentic but has filler phrases or explains the obvious
   - 2: Direct, confident, shows don't tell — the reader connects the dots

Verdict: "pass" if total >= {threshold}, otherwise "revise"
"""

_HIRING_MANAGER_QUESTIONS = """
Before scoring, read the letter as a hiring manager and answer these questions honestly:

1. After reading the opener, do I know WHY this person is writing to MY company specifically?
   Or could this opener be pasted into any application?

2. After reading the impact paragraph, do I understand what this person ACTUALLY built
   and what happened because of it? Or is it vague?

3. Does any sentence repeat an idea from a previous sentence? Read each sentence and check
   if the previous paragraph already made the same point. Flag ALL redundancies.

4. Is there any sentence that narrates the connection instead of showing it?
   Examples: "This is a natural fit for...", "This experience will enable me to contribute to...",
   "leveraging my expertise in X to drive impact at Y". These must be flagged.

5. Would I actually want to schedule a call with this person? Or does the letter feel
   like it was generated by a template? Be brutally honest.

6. Can I tell what this person would DO on day one if I hired them?
   Or are they just listing past experiences without connecting to my team's work?

Your feedback MUST reference these questions. Quote specific phrases that fail each test.
"""


class HiringManagerAgent(BaseAgent[ReviewVerdict]):
    """
    Reviews a cover letter draft as a hiring manager who has full context:
    the draft itself, the company research brief, and the JD requirements.

    This gives meaningfully different feedback than just reading the draft alone —
    it can evaluate whether the CL actually addresses company-specific needs.
    """

    agent_name = "reviewer"
    temperature = 0.2

    def system_prompt(self, **kwargs: Any) -> str:
        role_title: str = kwargs.get("role_title", "the role")
        company_name: str = kwargs.get("company_name", "the company")
        round_number: int = kwargs.get("round_number", 1)
        pass_threshold: float = kwargs.get("pass_threshold", settings.pipeline_pass_threshold)

        scoring_rubric = _SCORING_RUBRIC_TEMPLATE.format(threshold=pass_threshold)

        return (
            f"You are a senior hiring manager at {company_name} reviewing a cover letter "
            f"for the {role_title} position. Review round {round_number}. "
            f"You MUST respond with valid JSON only. No plain text. No code fences.\n\n"

            f"YOUR MINDSET: You read 50 cover letters a day. Most are templates with the "
            f"company name swapped in. You're looking for the ONE person who clearly "
            f"understands what your team is building and shows they can contribute on day one. "
            f"Generic letters go straight to the reject pile.\n\n"

            f"STEP 1 — Answer these questions honestly before scoring:\n"
            f"{_HIRING_MANAGER_QUESTIONS}\n\n"

            f"STEP 2 — Score using this rubric:\n{scoring_rubric}\n\n"

            f"STEP 3 — Write feedback:\n"
            f"- Identify the SPECIFIC phrase that fails — describe it in plain text, do NOT "
            f"wrap it in quotation marks inside your JSON strings (unescaped quotes break JSON)\n"
            f"- Say what to write INSTEAD, not just what's wrong\n"
            f"- Flag ALL redundancies — if two sentences make the same point, say which to cut\n"
            f"- Flag ALL connection-narrating ('natural fit for', 'will enable me to contribute')\n"
            f"- Check the banned_phrases list in the user message — any match = Voice score 0\n"
            f"- On revision rounds: acknowledge what improved and what still needs work\n\n"

            f"Respond ONLY with valid JSON:\n"
            f'{{"score": 7.5, "verdict": "pass", '
            f'"overall_impression": "one sentence", '
            f'"feedback": ["specific item 1", "specific item 2"], '
            f'"strengths": ["what worked 1"], '
            f'"areas_for_improvement": ["specific fix 1"]}}\n'
            f"Do not wrap in code fences."
        )

    def build_user_message(self, **kwargs: Any) -> str:
        draft: CoverLetterDraft = kwargs["draft"]
        research_brief: ResearchBrief = kwargs["research_brief"]
        jd_text: str = kwargs.get("jd_text", "")
        kit: CoverLetterKit = kwargs["kit"]

        payload = {
            "cover_letter": draft.content_md,
            "word_count": draft.word_count,
            "company_context": research_brief.company_context,
            "role_themes_from_research": research_brief.role_themes,
            "jd_requirements": research_brief.jd_requirements,
            "jd_excerpt": jd_text[:1500],
            "expected_tone_rules": {
                "overall": kit.tone.overall,
                "dislikes": kit.tone.dislikes,
                "dos": kit.dos,
                "donts": kit.donts,
            },
            "candidate_matched_experiences": research_brief.matched_experiences,
            "banned_phrases": BANNED_PHRASES,
        }
        return json.dumps(payload, ensure_ascii=False)

    def parse_response(self, raw: dict[str, Any]) -> ReviewVerdict:
        raw_score = raw.get("score", 0)
        try:
            score = float(raw_score)
        except (TypeError, ValueError):
            score = 0.0

        verdict = raw.get("verdict", "revise")
        if verdict not in ("pass", "revise"):
            verdict = "pass" if score >= settings.pipeline_pass_threshold else "revise"

        return ReviewVerdict(
            score=round(score, 1),
            verdict=verdict,
            overall_impression=raw.get("overall_impression", ""),
            feedback=list(raw.get("feedback", [])),
            strengths=list(raw.get("strengths", [])),
            areas_for_improvement=list(raw.get("areas_for_improvement", [])),
        )
